version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    restart: always
    container_name: sql-server-container
    environment:
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
    ports:
      - "1433:1433"
    volumes:
      - "./sql:/data/db"